#pragma once
//==============================================================================
//  Central-moment collision for a charge carrier driven by an electric field.
//
//  Patnaik, Skillen & De Rosis, Engineering with Computers 41:4977-5002 (2025),
//  the charge half of the EHD scheme. Transports
//
//      d_t q + div[ q (u + K E) ] = D grad^2 q
//
//  where u is the fluid velocity, E the electric field and K the ionic
//  mobility. Generated by MATLAB/D3Q27_CM_EHD.m, whose `Lq` and `heq` are the
//  authority for everything below.
//
//  ================== WHY THIS IS NOT ScalarBGK ON D3Q27 =====================
//  Two differences, and both matter.
//
//  THE ADVECTING VELOCITY IS NOT THE FLUID'S. It is u + K E, the fluid velocity
//  plus the ion drift. ScalarSolver already takes the advecting velocity as
//  three arbitrary Views, so the plumbing exists -- but this operator is handed
//  the DRIFT velocity and takes its central moments about that, which is what
//  makes the equilibrium sit where the transport actually goes.
//
//  THE EQUILIBRIUM IS FULL ORDER, NOT FIRST. ScalarBGK truncates at O(u)
//  deliberately, and its banner argues why: on D3Q7 and D2Q5 every velocity has
//  a single nonzero component, so (c.u)^2 collapses to c_a^2 u_a^2 and the
//  cross terms cannot be represented at all -- a second-order term there adds
//  anisotropy rather than accuracy. NONE OF THAT APPLIES ON D3Q27, which is a
//  product lattice with an isotropic fourth-order moment, and the paper is
//  explicit that the highest order the lattice supports "markedly improves
//  stability and fidelity in strongly forced regimes".
//
//  THE SIXTH-ORDER HERMITE EQUILIBRIUM IS THE PRODUCT-FORM EQUILIBRIUM, and
//  recognising that is what makes this operator four lines. The generator writes
//  heq as an explicit Hermite sum to sixth order; on a product lattice that sum
//  IS the discrete Maxwellian. So there is no new equilibrium to write.
//
//  AND IN THIS BASIS IT IS ALMOST ENTIRELY ZERO. ProductBasis is SHIFTED --
//  phi_2(C) = C^2 - cs2, not C^2 -- and its banner records the consequence: the
//  product-form equilibrium has exactly one nonzero moment, k_{0..0} = q, and
//  every other equilibrium moment vanishes identically. Taking the moments
//  about the drift velocity makes the first-order equilibrium zero too. So the
//  whole collision is:
//
//      keep q, decay the three fluxes by (1 - omega), zero everything else.
//
//  THE REFERENCE'S NUMBERS LOOK DIFFERENT AND ARE NOT. Q27_CM_EHD.cpp sets
//  k9 = Q, k17 = Q cs2, k18 = Q cs4, k26 = Q cs6 -- the (000), (200), (220) and
//  (222) slots of the MONOMIAL central moments, which is the basis its own
//  transform uses. Those same states are zero here because this basis has the
//  cs2 subtracted into the basis function instead. CLAUDE.md names this trap
//  first among the ones that break silently, and it fired while this file was
//  being written: the test asserted q cs2^n in the monomial basis, the operator
//  correctly produced zero, and the disagreement was the basis and not the
//  physics. Transcribing that moment list slot-for-slot would have been wrong
//  in a way that still conserves charge and still runs.
//
//  ================== THE RELAXATION SCHEDULE, WHICH IS THE POINT =============
//  From the generator, verbatim:
//
//      Lq = diag([1, omegaq, omegaq, omegaq, 1, 1, ... , 1])
//
//  The zeroth moment is conserved, the THREE FLUX moments relax at omega_q, and
//  every other moment goes straight to equilibrium. That is the same structure
//  as ScalarRegularised -- relax the flux, annihilate the ghosts -- which is why
//  that operator can be read as this one's D3Q7 special case. The difference is
//  that D3Q7 admits a closed-form inverse and D3Q27 does not, so this one goes
//  through ProductBasis's factorised transform.
//
//  It also means the pre-collision state barely matters: only the zeroth and
//  first central moments survive into the post-collision state, so the
//  reconstruction needs Q and the three fluxes and nothing else. The full
//  27-moment forward transform is still taken, because the flux moments are
//  what it computes; the saving is that no ghost is ever relaxed.
//
//  DIFFUSIVITY. D = cs2 (1/omega_q - 1/2) with cs2 = 1/3 on D3Q27, so
//  omega_from_diffusivity reads the lattice's own cs2 exactly as ScalarBGK's
//  does -- and, unlike D3Q7, here the closed form tau = 3D + 1/2 happens to be
//  right. Do not carry that coincidence to another lattice.
//
//  RAW STORAGE. The charge is O(q0) rather than O(1), so there is no universal
//  reference to shift against the way the fluid shifts against w_i. A shifted
//  variant is a reasonable future experiment -- the same argument that bought
//  0.8 decimal digits for the fluid applies -- but the reference implementation
//  is raw and matching it is worth more than the digits until the two agree.
//==============================================================================
#include "collision/ProductBasis.hpp"
#include "core/Types.hpp"
#include "lattice/Lattices.hpp"
#include "grid/Domain.hpp"
#include "memory/Storage.hpp"

#include <utility>   // integer_sequence -- the moment loop is unrolled

namespace lbm {

template <class L>
struct ChargeCentralMoments {
  using Lattice = L;
  using Storage = RawPopulations;
  using Basis   = ProductBasis<L>;
  static constexpr const char* name = "ChargeCentralMoments";
  static constexpr int D  = L::D;
  static constexpr int NM = Basis::NM;

  static_assert(Basis::enabled,
                "ChargeCentralMoments needs a product lattice (D2Q9 or D3Q27); "
                "D3Q19 has no product basis.");

  Real omega = Real(1);          // relaxes the flux, and so sets the diffusivity

  static Real omega_from_diffusivity(Real d) {
    return Real(1) / (d * inv_cs2<L, Real>() + Real(0.5));
  }
  static Real diffusivity_from_omega(Real w) {
    return (Real(1) / w - Real(0.5)) * cs2<L, Real>();
  }

  KOKKOS_INLINE_FUNCTION
  static Real charge(const Real h[L::Q]) {
    Real s = Real(0);
    for (int i = 0; i < L::Q; ++i) s += h[i];
    return s;
  }

  //----------------------------------------------------------------------------
  //  ScalarSolver's collision interface, so this drops into the existing solver
  //  rather than needing one of its own. The names are the scalar solver's
  //  (`temperature`, `T_ref`) because that is the concept it calls; here they
  //  mean charge. The advecting velocity ScalarSolver passes through is the
  //  DRIFT velocity u + K E, which the driver supplies via set_velocity -- that
  //  hook already takes three arbitrary Views and does not care where they came
  //  from, which is why no plumbing is needed for the drift.
  //----------------------------------------------------------------------------
  Real T_ref = Real(0);          // no shift; see the storage note in the banner
  View1D<Real> omega_of;         // unused here, kept for interface compatibility

  // Deviation from the storage reference. T_ref is 0 here, so this IS the
  // charge; the name is ScalarSolver's concept and is kept for that reason.
  KOKKOS_INLINE_FUNCTION
  static Real deviation(const Real h[L::Q]) { return charge(h); }

  KOKKOS_INLINE_FUNCTION Real temperature(const Real h[L::Q]) const {
    return T_ref + charge(h);
  }
  KOKKOS_INLINE_FUNCTION Real omega_at(Index) const { return omega; }

  KOKKOS_INLINE_FUNCTION
  Real eq(int i, Real dq, Real kux, Real kuy, Real kuz) const {
    return seed_value(i, T_ref + dq, kux, kuy, kuz);
  }

  // The dq ScalarSolver hands in is the same zeroth moment `to_moments` will
  // compute, so it is not used; taking it from the transform keeps the two
  // from ever disagreeing.
  KOKKOS_INLINE_FUNCTION
  void collide(Real h[L::Q], Real, Real kux, Real kuy, Real kuz, Real w) const {
    collide(h, kux, kuy, kuz, w);
  }

  //----------------------------------------------------------------------------
  //  Everything of order 2 and above goes to zero -- see the banner: in this
  //  shifted basis that IS the equilibrium. N is a TEMPLATE parameter and must
  //  stay one: with a runtime index the basis's 432-byte exponent table is
  //  materialised in memory and takes the moment array with it. See
  //  MomentCollision.hpp's eq_moment banner for the measurement, and
  //  tests/frame_check.sh for the instrument.
  //----------------------------------------------------------------------------
  using Moments = std::make_integer_sequence<int, NM>;

  template <int N>
  KOKKOS_INLINE_FUNCTION
  static void zero_one(Real k[NM]) {
    if constexpr (Basis::order(N) >= 2) k[N] = Real(0);
  }
  template <int... N>
  KOKKOS_INLINE_FUNCTION
  static void zero_rest(Real k[NM], std::integer_sequence<int, N...>) {
    (zero_one<N>(k), ...);
  }

  //----------------------------------------------------------------------------
  //  kux, kuy, kuz are the DRIFT velocity u + K E, not the fluid velocity.
  //----------------------------------------------------------------------------
  KOKKOS_INLINE_FUNCTION
  void collide(Real h[L::Q], Real kux, Real kuy, Real kuz, Real w) const {
    const Real ub[3] = {kux, kuy, kuz};

    // Central moments ABOUT THE DRIFT VELOCITY, so the equilibrium's first
    // moment is identically zero and the flux moment IS the non-equilibrium
    // part -- which is what makes the relaxation below one multiply.
    Real k[NM];
    Basis::template to_moments<true>(h, ub, k);

    // ---- order 1: the flux, and the only thing that relaxes ----
    // The equilibrium first moment about the drift velocity is zero, so the
    // relaxation is a pure decay rather than a relaxation towards anything.
    // These axis subscripts fold: D is 2 or 3 and i1() is constexpr.
    for (int a = 0; a < D; ++a) k[i1(a)] *= (Real(1) - w);

    // ---- order 0: conserved, untouched. order >= 2: to equilibrium, i.e. 0 ----
    zero_rest(k, Moments{});

    Basis::template to_populations<true>(k, ub, h);
  }
  KOKKOS_INLINE_FUNCTION
  void collide(Real h[L::Q], Real kux, Real kuy, Real kuz) const {
    collide(h, kux, kuy, kuz, omega);
  }

  //----------------------------------------------------------------------------
  // Equilibrium populations at a given charge and drift velocity. Initialisation
  // and boundary reconstruction.
  //----------------------------------------------------------------------------
  KOKKOS_INLINE_FUNCTION
  static Real seed_value(int i, Real q, Real kux, Real kuy, Real kuz) {
    const Real ub[3] = {kux, kuy, kuz};
    Real k[NM], h[L::Q];
    for (int m = 0; m < NM; ++m) k[m] = Real(0);
    k[0] = q;                                  // the whole equilibrium, in one slot
    Basis::template to_populations<true>(k, ub, h);
    return h[i];
  }

 private:
  // Flux slot for axis a, located through the basis rather than hardcoded.
  static constexpr int i1(int a) {
    return Basis::index_of(a == 0, a == 1, (D == 3) && a == 2);
  }
};

}  // namespace lbm
